CC = gcc
CFLAGS = -Wall -g
all: fib_rec fib_dyn fib_memo
fib_rec:
	$(CC) $(CFLAGS) -o fib_rec fib_rec.c
fib_dyn:
	$(CC) $(FLAGS) -o fib_dyn fib_dyn.c
fib_memo:
	$(CC) $(FLAGS) -o fib_memo fib_memo.c
clean:
	rm -r fib_rec fib_dyn fib_memo
